baseURL = "/"
languageCode = "en-US"
defaultContentLanguage = "en"

title = "ElegantLaTeX Program"
theme = "hugo-theme-learn"
themesdir = "./themes/."
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= true
publishDir = "docs"

[params]
  description = "Documentation for ElegantLaTeX Templates"
  author = "ElegantLaTeX"
  showVisitedLinks = true
  disableBreadcrumb = false
  disableNextPrev = true

[outputs]
home = [ "HTML", "RSS", "JSON"]

[Languages]
[Languages.en]
title = "Documentation for ElegantLaTeX Templates"
weight = 1
languageName = "English"

[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> Github repo"
identifier = "ds"
url = "https://github.com/ElegantLaTeX"
weight = 10

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-fw fa-camera'></i> Showcases"
url = "showcase"
weight = 11

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-fw fa-bookmark'></i> Hugo"
identifier = "hugodoc"
url = "https://gohugo.io/"
weight = 20



[Languages.cn]
title = "ElegantLaTeX 系列模板文档说明"
weight = 2
languageName = "Chinese"

[[Languages.cn.menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> Github"
identifier = "ds"
url = "https://github.com/ElegantLaTeX"
weight = 10

[[Languages.cn.menu.shortcuts]]
name = "<i class='fas fa-fw fa-camera'></i> 截图"
url = "/showcase"
weight = 11

[[Languages.cn.menu.shortcuts]]
name = "<i class='fas fa-fw fa-bookmark'></i> 文档"
identifier = "hugodoc"
url = "https://gohugo.io/"
weight = 20

[[Languages.en.menu.Title]]
other = "Links"



